# Site settings
title: Sam Mazzuca
description: A brief summary
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oxfordfictionary.github.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sam Mazzuca
user_description: I'm a student at Lambda School with specific interest in machine learning, neural style transfer, data analytics, and data engineering. Stay tuned for my projects.
user_title: Data Science Student
email: sam.a.mazzuca@gmail.com
twitter_username: LambdaSigma2
github_username:  oxfordfictionary
# gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
